

services:
  postgres:
    image: postgres:15
    container_name: tourist_postgres
    environment:
      POSTGRES_USER: tourist
      POSTGRES_PASSWORD: tourist123
      POSTGRES_DB: touristdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tourist_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tourist_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  pgdata:
